CREATE TABLE  codegens (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
code VARCHAR( 10 ) NOT NULL ,
phone VARCHAR( 10 ) NOT NULL ,
used BOOL NOT NULL DEFAULT FALSE,
createdat DATETIME NOT NULL
) ENGINE = INNODB;

CREATE TABLE  players (
id BIGINT NOT NULL PRIMARY KEY ,
code VARCHAR( 10 ) NOT NULL ,
gsm VARCHAR( 10 ) NOT NULL ,
nom VARCHAR(254) NOT NULL,
prenom VARCHAR(254) NOT NULL,
age VARCHAR(10) NOT NULL,
email VARCHAR(254) NOT NULL,
ami VARCHAR(10),
cadeau SMALLINT,
createdat DATETIME NOT NULL
) ENGINE = INNODB;

CREATE TABLE  oplayers (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
code VARCHAR( 10 ) NOT NULL ,
gsm VARCHAR( 10 ) NOT NULL ,
nom VARCHAR(254) NOT NULL,
prenom VARCHAR(254) NOT NULL,
age VARCHAR(10) NOT NULL,
email VARCHAR(254) NOT NULL,
ami VARCHAR(10),
createdat DATETIME NOT NULL
) ENGINE = INNODB;

CREATE TABLE winners (
num BIGINT NOT NULL PRIMARY KEY ,
cadeau SMALLINT NOT NULL,
used BOOL NOT NULL DEFAULT FALSE,
createdat DATETIME NOT NULL
) ENGINE = INNODB;

CREATE TABLE admins (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
login VARCHAR(254) NOT NULL,
passwd VARCHAR(254) NOT NULL
) ENGINE = INNODB;